### ISSUE TITLE
Error for particular stations; stream url: addrad.io

### ISSUE THREAD

**Issue by MasteRehm** [dersphere/plugin.audio.radio_de#15]
Hi,

first things first: Thx for the plugin.
Since a couple of weeks I can't play my favourite station, SWR1. I can't also play other stations from this radio group, e.g. SWR3. All of them have one in common: The stream url, addrad.io. If  I am going to open `http://addrad.io/4WRLzg` in my Browser or VLC, everything works fine.
So I guess, there's something fishy with the plugin handling stream urls from addrad.io.
Can you please have a look?
```
08:57:18.865 T:140701174064896  NOTICE: [xbmcswift2] Request for "/station/2273" matches rule for function "get_stream_url"
08:57:18.865 T:140701174064896  NOTICE: [plugin.audio.radio_de] get_station_by_station_id started with station_id=2273
08:57:18.865 T:140701174064896  NOTICE: [plugin.audio.radio_de] __api_call started with path=broadcast/getbroadcastembedded, param={'broadcast': '2273'}
08:57:18.865 T:140701174064896  NOTICE: [plugin.audio.radio_de] __urlopen opening url=http://rad.io/info/broadcast/getbroadcastembedded?broadcast=2273
08:57:18.961 T:140701174064896  NOTICE: [plugin.audio.radio_de] get_stream_url result: http://addrad.io/4WRLzg
08:57:39.739 T:140704177832064   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
08:57:39.790 T:140704177832064   ERROR: Open - error probing input format, http://addrad.io/4WRLzg
08:57:39.790 T:140704177832064   ERROR: Init: Error creating demuxer
08:57:39.790 T:140704177832064   ERROR: CAudioDecoder: Unable to Init Codec while loading file http://addrad.io/4WRLzg
08:57:39.790 T:140704177832064 WARNING: PAPlayer::QueueNextFileEx - Failed to create the decoder
```

**Comment by SkyBird1980** [comment]
Same for Radio Bob!
`12:10:06.279 T:11284  NOTICE: [plugin.audio.radio_de] search_stations_by_string started with search_string=bob
12:10:06.279 T:11284  NOTICE: [plugin.audio.radio_de] __api_call started with path=index/searchembeddedbroadcast, param={'q': 'bob', 'start': '0', 'rows': '10000', 'streamcontentformats': 'aac,mp3'}
12:10:06.279 T:11284  NOTICE: [plugin.audio.radio_de] __urlopen opening url=http://radio.de/info/index/searchembeddedbroadcast?q=bob&start=0&rows=10000&streamcontentformats=aac%2Cmp3
12:10:06.737 T:11284  NOTICE: [plugin.audio.radio_de] __add_stations started with 293 items
12:10:20.691 T:8404  NOTICE: [xbmcswift2] Request for "/station/37980" matches rule for function "get_stream_url"
12:10:20.691 T:8404  NOTICE: [plugin.audio.radio_de] get_station_by_station_id started with station_id=37980
12:10:20.691 T:8404  NOTICE: [plugin.audio.radio_de] __api_call started with path=broadcast/getbroadcastembedded, param={'broadcast': '37980'}
12:10:20.691 T:8404  NOTICE: [plugin.audio.radio_de] __urlopen opening url=http://radio.de/info/broadcast/getbroadcastembedded?broadcast=37980
12:10:20.734 T:8404  NOTICE: [plugin.audio.radio_de] get_stream_url result: http://streams.radiobob.de/bob-deutsch/mp3-128/radiode/
12:10:42.934 T:9884   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
12:10:42.988 T:9884   ERROR: CDVDDemuxFFmpeg::Open - error probing input format, http://streams.radiobob.de/bob-deutsch/mp3-128/radiode/
12:10:42.988 T:9884   ERROR: VideoPlayerCodec::Init: Error creating demuxer
12:10:42.988 T:9884   ERROR: CAudioDecoder: Unable to Init Codec while loading file http://streams.radiobob.de/bob-deutsch/mp3-128/radiode/
12:10:42.988 T:9884 WARNING: PAPlayer::QueueNextFileEx - Failed to create the decoder`

**Comment by waeller** [comment]
Same for Deutschlandfunk Stations, or (in the following log) BR Klassik:

    20:57:03.823 T:1308029856  NOTICE: [xbmcswift2] Request for "/station/2248" matches rule for function "get_stream_url"
    20:57:03.824 T:1308029856  NOTICE: [plugin.audio.radio_de] get_station_by_station_id started with station_id=2248
    20:57:03.825 T:1308029856  NOTICE: [plugin.audio.radio_de] __api_call started with path=broadcast/getbroadcastembedded, param={'broadcast': '2248'}
    20:57:03.825 T:1308029856  NOTICE: [plugin.audio.radio_de] __urlopen opening url=http://radio.de/info/broadcast/getbroadcastembedded?broadcast=2248
    20:57:03.939 T:1308029856  NOTICE: [plugin.audio.radio_de] get_stream_url result: http://addrad.io/4WRDqw
    20:57:25.018 T:1961857024   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
    20:57:25.022 T:1961857024   ERROR: Open - error probing input format, http://addrad.io/4WRDqw
    20:57:25.023 T:1961857024   ERROR: Init: Error creating demuxer
    20:57:25.023 T:1961857024   ERROR: CAudioDecoder: Unable to Init Codec while loading file http://addrad.io/4WRDqw
    20:57:25.023 T:1961857024 WARNING: PAPlayer::QueueNextFileEx - Failed to create the decoder
    20:57:25.024 T:1961857024   ERROR: Playlist Player: skipping unplayable item: 9, path [plugin://plugin.audio.radio_de/station/2248]

In a browser, the addrad.io link works, it's a redirect to the actual stream URL. Maybe this redirect is a problem?

**Comment by nafets83** [comment]
Same here for Berlin 88.8.
`08:22:51.345 T:18446744071943995904  NOTICE: [xbmcswift2] Request for "/station/2257" matches rule for function "get_stream_url"
08:22:51.346 T:18446744071943995904  NOTICE: [plugin.audio.radio_de] get_station_by_station_id started with station_id=2257
08:22:51.348 T:18446744071943995904  NOTICE: [plugin.audio.radio_de] __api_call started with path=broadcast/getbroadcastembedded, param={'broadcast': '2257'}
08:22:51.350 T:18446744071943995904  NOTICE: [plugin.audio.radio_de] __urlopen opening url=http://radio.de/info/broadcast/getbroadcastembedded?broadcast=2257
08:22:52.370 T:18446744071943995904  NOTICE: [plugin.audio.radio_de] get_stream_url result: http://addrad.io/4WRKrD
08:23:18.188 T:18446744072444047616   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
08:23:18.574 T:18446744072444047616   ERROR: Open - error probing input format, http://addrad.io/4WRKrD
08:23:18.580 T:18446744072444047616   ERROR: Init: Error creating demuxer
08:23:18.581 T:18446744072444047616   ERROR: CAudioDecoder: Unable to Init Codec while loading file http://addrad.io/4WRKrD
08:23:18.581 T:18446744072444047616 WARNING: PAPlayer::QueueNextFileEx - Failed to create the decoder
08:23:18.804 T:18446744072444047616   ERROR: Playlist Player: skipping unplayable item: 2, path [plugin://plugin.audio.radio_de/station/2257]
08:23:58.581 T:18446744071927598720  NOTICE: [xbmcswift2] Request for "/station/2257" matches rule for function "get_stream_url"
08:23:58.582 T:18446744071927598720  NOTICE: [plugin.audio.radio_de] get_station_by_station_id started with station_id=2257
08:23:58.583 T:18446744071927598720  NOTICE: [plugin.audio.radio_de] __api_call started with path=broadcast/getbroadcastembedded, param={'broadcast': '2257'}
08:23:58.584 T:18446744071927598720  NOTICE: [plugin.audio.radio_de] __urlopen opening url=http://radio.de/info/broadcast/getbroadcastembedded?broadcast=2257
08:23:59.279 T:18446744071927598720  NOTICE: [plugin.audio.radio_de] get_stream_url result: http://addrad.io/4WRKrD
08:24:26.351 T:18446744072444047616   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
08:24:26.363 T:18446744072444047616   ERROR: Open - error probing input format, http://addrad.io/4WRKrD
08:24:26.366 T:18446744072444047616   ERROR: Init: Error creating demuxer
08:24:26.366 T:18446744072444047616   ERROR: CAudioDecoder: Unable to Init Codec while loading file http://addrad.io/4WRKrD
08:24:26.367 T:18446744072444047616 WARNING: PAPlayer::QueueNextFileEx - Failed to create the decoder
08:24:26.402 T:18446744072444047616   ERROR: Playlist Player: skipping unplayable item: 2, path [plugin://plugin.audio.radio_de/station/2257]`

**Comment by TheNoTwist** [comment]
I have same Problem with SWR3:

`22:51:38.332 T:1628435376  NOTICE: [xbmcswift2] Request for "/" matches rule for function show_root_menu"`
`22:51:42.737 T:1895822256  NOTICE: [xbmcswift2] Request for "/stations/local/" matches rule for function "show_local_stations"`
`22:51:42.738 T:1895822256  NOTICE: [plugin.audio.radio_de] get_local_stations started with num_entries=25`
`22:51:42.738 T:1895822256  NOTICE: [plugin.audio.radio_de] get_most_wanted started with num_entries=25`
`22:51:42.739 T:1895822256  NOTICE: [plugin.audio.radio_de] __api_call started with path=account/getmostwantedbroadcastlists, param={'sizeoflists': '25'}`
`22:51:42.740 T:1895822256  NOTICE: [plugin.audio.radio_de] __urlopen opening url=http://radio.de/info/account/getmostwantedbroadcastlists?sizeoflists=25`
`22:51:43.550 T:1895822256  NOTICE: [plugin.audio.radio_de] __add_stations started with 20 items`
`22:51:48.417 T:1628435376  NOTICE: [xbmcswift2] Request for "/station/2275" matches rule for function "get_stream_url"`
`22:51:48.418 T:1628435376  NOTICE: [plugin.audio.radio_de] get_station_by_station_id started with station_id=2275`
`22:51:48.418 T:1628435376  NOTICE: [plugin.audio.radio_de] __api_call started with path=broadcast/getbroadcastembedded, param={'broadcast': '2275'}`
`22:51:48.419 T:1628435376  NOTICE: [plugin.audio.radio_de] __urlopen opening url=http://radio.de/info/broadcast/getbroadcastembedded?broadcast=2275`
`22:51:48.532 T:1628435376  NOTICE: [plugin.audio.radio_de] get_stream_url result: http://addrad.io/4WRLM8`
`22:52:10.513 T:1945592480   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)`
`22:52:10.519 T:1945592480   ERROR: Open - error probing input format, http://addrad.io/4WRLM8`
`22:52:10.520 T:1945592480   ERROR: Init: Error creating demuxer`
`22:52:10.520 T:1945592480   ERROR: CAudioDecoder: Unable to Init Codec while loading file http://addrad.io/4WRLM8`
`22:52:10.520 T:1945592480 WARNING: PAPlayer::QueueNextFileEx - Failed to create the decoder`
`22:52:10.521 T:1945592480   ERROR: Playlist Player: skipping unplayable item: 0, path plugin://plugin.audio.radio_de/station/2275]`


On the website radio.de the stream is working. 
TuneIn Radio Addon is still playing SWR3.

**Comment by Neox666x** [comment]
Hi
Since today no Radio staion is working on Kodi 17 Kryxpton with Radio app.
App from Radio.de on android works fine.

**Comment by dersphere** [comment]
Fixed with 63d7fe623ccb2a46c271e82f6556d6274d95b493
I will upload the new version to the gotham repository, it will be available in a few days via auto-update (gotham and above).

**Comment by Schnoogemetzger** [comment]
Thanks. I'll give you feedback as soon it's available.

**Comment by waeller** [comment]
Thanks! Version 2.3.2 is working fine again. :)

**Comment by Schnoogemetzger** [comment]
I agree with @waeller, works like a charm.

**Comment by jenspf** [comment]
Hi Guys.
For some reason still not all streams can be played.
e.g.    http://streams.radiobob.de/bob-live/mp3-128/streams.radiobob.de/ 
is not working. Others are playing correct now, like hr3.de
Whats the issue with this stream of my favourite station? 
Its playing with my VLC player right away but not w/ Kodi.
Cheers Jens

**Comment by dersphere** [comment]
Please provide a kodi.log (debug not needed) while you are trying to play this station.

**Comment by jenspf** [comment]
OK, I restarted my Pi, searched for radiobob, stream couldn't start, then I searched for a station called hr1 and the stream started playing . Just to proof that kodi is actually playing streams.
Thanks for your help. Cheers Jens
[kodi.log.txt](https://github.com/dersphere/plugin.audio.radio_de/files/1069612/kodi.log.txt)

**Comment by Neox666x** [comment]
Hi 
FFH Rock Stream doesn't Work too...

Cheers Thomas

**Comment by jenspf** [comment]
Hi dersphere. Any idea on whats the problem? Cheers Jens

**Comment by jenspf** [comment]
Hi dersphere. You're still there? :-)

**Comment by jenspf** [comment]
Hi dersphere.
 I updated my pi as well as the radio addon two days ago. Still the same issue. You think you can help?
@ Thomas any news on your side?
Cheers Jens

**Comment by jenspf** [comment]
Sorry is this thread dead or what? Hellooo, Mc Fly, anybody home?

**Comment by Schnoogemetzger** [comment]
Just fyi @jenspf, this is not a thread, this is a bug resp. issue report and it's closed. Maybe you want to open a new one.

**Comment by Neox666x** [comment]
Hi
Leider ist es mal wieder soweit.
Ein paar Radio Stationen werden mal wieder nicht abgespielt.
Momentan bei mir hr Sender , FFH Sender; Bayern Sender und Harmony fm......

Hab leider noch kein log zum mitschicken muss ich erst wieder durch wurschteln wo ich das finde..... 

Könnten Sie sich das mal anschauen?

Danke
Gruß Thomas Rinn 
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 12.06.17, 22:07, Tristan Fischer <notifications@github.com> schrieb:
Please provide a kodi.log (debug not needed) while you are trying to play this station.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dersphere/plugin.audio.radio_de","title":"dersphere/plugin.audio.radio_de","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dersphere/plugin.audio.radio_de"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dersphere in #15: Please provide a kodi.log (debug not needed) while you are trying to play this station."}],"action":{"name":"View Issue","url":"https://github.com/dersphere/plugin.audio.radio_de/issues/15#issuecomment-307909231"}}}
